stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  script:
    - echo Building project 
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u "$CI_REGISTRY_USER" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  tags:
    - docker1  

deploy:
  stage: deploy
  image: jonaskello/docker-and-compose
  script:
    - echo Deploy project
    - docker login -u "$CI_REGISTRY_USER" -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose up -d
    
  tags:
    - docker1
    
